// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCpWIWnBGA0X6ExtfWIvGm4G5a9iZJHKM',
    appId: '1:501860739341:web:644d9233c368e2d1542844',
    messagingSenderId: '501860739341',
    projectId: 'chatapp-7e54e',
    authDomain: 'chatapp-7e54e.firebaseapp.com',
    storageBucket: 'chatapp-7e54e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOJTTWr5NKSlfgWm-Ar6_WGArOrNRhsHg',
    appId: '1:501860739341:android:a7f330c30ddaad2c542844',
    messagingSenderId: '501860739341',
    projectId: 'chatapp-7e54e',
    storageBucket: 'chatapp-7e54e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMzm5R93d8OmiuiRkLft-m3MoSeVCcjW0',
    appId: '1:501860739341:ios:7190fd7cd448ea67542844',
    messagingSenderId: '501860739341',
    projectId: 'chatapp-7e54e',
    storageBucket: 'chatapp-7e54e.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMzm5R93d8OmiuiRkLft-m3MoSeVCcjW0',
    appId: '1:501860739341:ios:0ad32fcb244faa05542844',
    messagingSenderId: '501860739341',
    projectId: 'chatapp-7e54e',
    storageBucket: 'chatapp-7e54e.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
